services:
  api:
    build: ./.docker/api
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    volumes:
      - ./:/pkg:cached
      - ./.docker/api/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
  db:
    build: ./.docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    ports:
      - "13306:3306"
    volumes:
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./api/logs:/var/log/mysql:delegated
      - v-db:/var/lib/mysql
  web:
    build: ./.docker/web
    # environment:
    ports:
      - "3000:3000"
    volumes:
      - ./:/pkg:cached
volumes:
  v-db:
